title: Digital Instrument Tuner
author: "Broderick Bownds and Sebastian Heredia"
theme: minima


project:  
  type: website

website:
  title: "Digital Instrument Tuner"
  navbar:
    left:
      - href: design.qmd
        text: Design
      - href: documentation.qmd
        text: Documentation
      - href: resources.qmd
        text: Resources

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true